plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':application')
    implementation project(':adapter-in-web')
    implementation project(':adapter-out-persistence')
    implementation project(':adapter-out-external')
    implementation 'io.micrometer:micrometer-registry-prometheus'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-web'
}

jar {
    enabled = false
}

bootJar {
    archiveFileName = 'baton-watch.jar'
}
